name: posterr
description: A post flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  jiffy: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  build_runner: ^2.3.0


flutter:

  uses-material-design: true

  
